package geoparser

import (
	//"fmt"

	"../types"
)

// Coord info
type Coord struct {
	Latitude  string
	Longitude string
	Geodata   types.AutoGenerated
}

//GetCityName fromGeoAPI
func (c *Coord) GetCityName() string {

	lenAddressComponents := len(c.Geodata.Results[0].AddressComponents)
	var city    = c.Geodata.Results[0].AddressComponents[lenAddressComponents-3].LongName
	var country = c.Geodata.Results[0].AddressComponents[lenAddressComponents-4].LongName
	return city + " " + country
}

// GetLatitude  write await
func (c *Coord) GetLatitude() string {
	return "huga"
}

// GetLongitude write await
func (c *Coord) GetLongitude() string {
	return "piyo"
}
