package geoparser

import (
	"strconv"

	"../types"
)

// Coord info
type Coord struct {
	Latitude  string
	Longitude string
	Geodata   types.AutoGenerated
}

type Address struct {
	City    string
	Town    string
	Geodata types.AutoGenerated
}

//GetCityName fromGeoAPI
func (c *Coord) GetCityName() string {

	lenAddressComponents := len(c.Geodata.Results[0].AddressComponents)
	var city = c.Geodata.Results[0].AddressComponents[lenAddressComponents-3].LongName
	return city
}

func (c *Coord) GetTownName() string {
	
	lenAddressComponents := len(c.Geodata.Results[0].AddressComponents)
	var town = c.Geodata.Results[0].AddressComponents[lenAddressComponents-4].LongName
	return town
}

// GetLatitude  write await
func (a *Address) GetLatitude() string {
	
	var latitude = a.Geodata.Results[0].Geometry.Location.Lat
	return strconv.FormatFloat(latitude, 'f',-1, 64)
}

// GetLongitude write await
func (a *Address) GetLongitude() string {
	
	var longitude = a.Geodata.Results[0].Geometry.Location.Lng
	return strconv.FormatFloat(longitude, 'f',-1, 64)
}
