package geoparser

import (
	"fmt"
	"strconv"
	"strings"

	"../types"
)

// Coord info
type Coord struct {
	Latitude  string
	Longitude string
	Geodata   types.AutoGenerated
}

type Address struct {
	City    string
	Town    string
	Geodata types.AutoGenerated
}

//GetCityName fromGeoAPI
func (c *Coord) GetCityName() string {

	lenAddressComponents := len(c.Geodata.Results[0].AddressComponents)
	city := c.Geodata.Results[0].AddressComponents[lenAddressComponents-3].LongName
	// 空白を置換しないとURLが壊れる
	return strings.Replace(city, " ", "-", -1)
}

func (c *Coord) GetTownName() string {

	lenAddressComponents := len(c.Geodata.Results[0].AddressComponents)
	town := c.Geodata.Results[0].AddressComponents[lenAddressComponents-4].LongName
	// 空白を置換しないとURLが壊れる
	return strings.Replace(town, " ", "-", -1)
}

// Println データを表示
func (c *Coord) Println() {
	fmt.Println(c.Geodata)
}

// GetLatitude  write await
func (a *Address) GetLatitude() string {

	var latitude = a.Geodata.Results[0].Geometry.Location.Lat
	return strconv.FormatFloat(latitude, 'f', -1, 64)
}

// GetLongitude write await
func (a *Address) GetLongitude() string {

	var longitude = a.Geodata.Results[0].Geometry.Location.Lng
	return strconv.FormatFloat(longitude, 'f', -1, 64)
}
